# Generated by Django 4.1.6 on 2023-02-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todolist_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активна'), ('NOT_ACTIVE', 'Неактивна')], default='ACTIVE', max_length=20, verbose_name='Статус'),
        ),
    ]
