# Generated by Django 4.1.6 on 2023-02-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todolist_date_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='удалено'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date_deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
